version: 0.2

phases:
  build:
    commands:
      - echo "Starting build process"
      - echo "No build steps required for static HTML."
  post_build:
    commands:
      - echo "Build complete. Preparing artifacts for deployment."

artifacts:
  files:
    - '**/*'             
  base-directory: '.'    
  discard-paths: yes     
  name: website_artifact 